#!/usr/bin/env bash
# A Bash script that displays all currently running processes, including those without a TTY, in a user-friendly hierarchical format
ps -eo user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,cmd --forest
