#!/usr/bin/env bash
# A Bash script that displays all currently running processes with USER, STARTED time (HH:MM:SS), and CMD in a hierarchical format
ps -eo user,lstart,cmd --forest | awk '
BEGIN {
    print "USER     STARTED   CMD"
}
NR > 1 {
    time = $(5)
    cmd = substr($0, index($0,$6))
    printf "%-8s %s %s\n", $1, time, cmd
}'
