#!/usr/bin/env bash
# This script handles SIGTERM signal
# Function to handle SIGTERM
handle_sigterm() {
    echo "SIGTERM signal received. Exiting gracefully..."
    exit 0
}
# Trap SIGTERM signal
trap 'handle_sigterm' SIGTERM
# Your script's main logic here
while true; do
    echo "I am invincible!!!"
    sleep 1
done
