#!/usr/bin/env bash
# Script runs an infinite loop and handles the SIGTERM signal
#+ a sleep 2 in between each iteration.
#  Displays "I am invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible"' SIGTERM 
done
