#!/usr/bin/env bash
# Get the PID(s) of the running 7-highlander process
pid=$(ps -eo pid,comm | awk '$2=="7-highlander" {print $1}')
# Kill the process if found
if [ -n "$pid" ]; then
  kill -9 "$pid"
fi
