#!/usr/bin/env bash
# Get the exact PID of the 7-highlander process using pgrep
pid=$(pgrep -f "^./7-highlander$")
# Kill it using SIGKILL (signal 9), only if a PID was found
if [ -n "$pid" ]; then
  kill -9 "$pid"
fi
