#!/usr/bin/env bash
# or you can use: #!/bin/bash

# Find the PID of the process named "7-highlander"
pid=$(pgrep -f "7-highlander")

# Kill the process using SIGKILL (signal 9), if found
if [ -n "$pid" ]; then
  kill -9 "$pid"
fi
