#!/bin/bash
#!/usr/bin/env bash.
# Display current directory content showing only part after first dash, no hidden files
for file in *; do
  if [[ "$file" == *-* ]]; then
    echo "${file#*-}"
  else
    echo "$file"
  fi
done
